### PR TITLE
Add unit test for radiance buffer save

### PR DESCRIPTION
**Pull request by unusual-thoughts**
I had to write the buffer to a temp file and then load that because there is no `radload_buffer`

### CODE REVIEW

**Comment by unusual-thoughts** [comment]
By the way, I am getting errors with gif loading:
```python
======================================================================
ERROR: test_gifload (__main__.TestForeign)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_foreign.py", line 417, in test_gifload
    self.buffer_loader("gifload_buffer", self.gif_file, gif_valid)
  File "test_foreign.py", line 77, in buffer_loader
    validate(self, im)
  File "test_foreign.py", line 410, in gif_valid
    a = im(10, 10)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Vips.py", line 846, in __call__
    return self.getpoint(x, y)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Vips.py", line 651, in call_function
    return _call_instance(self, name, args, kwargs)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Vips.py", line 426, in _call_instance
    return _call_base(name, args, kwargs, self)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Vips.py", line 376, in _call_base
    raise Error('Error calling operator %s.' % name)
gi.overrides.Vips.Error: Error calling operator getpoint.
  gifload_buffer: Failed to read from given file
vips__region_start: start function failed for image temp-891


======================================================================
ERROR: test_magickload (__main__.TestForeign)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_foreign.py", line 265, in test_magickload
    self.buffer_loader("magickload_buffer", self.gif_file, gif_valid)
  File "test_foreign.py", line 79, in buffer_loader
    validate(self, im)
  File "test_foreign.py", line 250, in gif_valid
    a = im(10, 10)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Vips.py", line 846, in __call__
    return self.getpoint(x, y)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Vips.py", line 651, in call_function
    return _call_instance(self, name, args, kwargs)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Vips.py", line 426, in _call_instance
    return _call_base(name, args, kwargs, self)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Vips.py", line 376, in _call_base
    raise Error('Error calling operator %s.' % name)
gi.overrides.Vips.Error: Error calling operator getpoint.
  gifload_buffer: Failed to read from given file
vips__region_start: start function failed for image temp-982


----------------------------------------------------------------------
```

**Comment by jcupitt** [comment]
Yes, the giflib in current Ubuntu (is that what you're using?) is totally broken, unfortunately. There's a bug report on launchpad but sadly it's not been fixed yet.

**Comment by jcupitt** [comment]
Here's the bug report:

https://bugs.launchpad.net/ubuntu/+source/giflib/+bug/1580376

If you click "affects me too" it might get fixed sooner, who knows.

**Comment by jcupitt** [comment]
Looks good, thanks!

**Comment by unusual-thoughts** [comment]
I'm using arch linux with giflib 5.1.2.
I just updated my packages, and giflib got bumped to 5.1.4 (the package was 4 days old), and you guessed it, problem is gone!

**Comment by jcupitt** [comment]
Phew! 

And thanks for adding this feature, it's a nice thing to have. Are you doing anything interesting with vips + radiance? I added rad support a few years ago when I was doing some HDR work, but I wasn't sure if anyone else was using it.

**Pull request merged**
