### PR TITLE
Fix Python and GI path detection problems

### PR DESCRIPTION
**Pull request by felixbuenemann**
* Vendor the pygobject `m4/python.m4` to fix wrong multiarch exec paths
* Fix several problems with gi path warnings
* Disable vips7 SWIG bindings for python3 (see #334)
* Warn if the gi module could not be loaded
* Fix `VIPS_LIBDIR` being `"NONE"` without explicit `--prefix`

For details see #438 and the individual commit messages.

### CODE REVIEW

**Comment by felixbuenemann** [comment]
Tested on Amazon Linux 2015.09, Precise, Trusty, Xenial, OS X 10.11 w/Homebrew.

Btw. warning the user that we know there is a problem still seems a bit clunky to me. I'll explore the idea of instead installing symlinks to the two `__init__.py` from the system gi path to the prefix path. That should be a lot less error prone that the stub approach.

**Comment by jcupitt** [comment]
That all looks great, nice job @felixbuenemann

**Comment by jcupitt** [comment]
I found a small problem: `acinclude.m4` had a version of `AM_CHECK_PYTHON_HEADERS` as well, I don't know which version was being used. Anyway, it was confusing.

I've broken the vips `acinclude.m4` up into a series of separate tests (`tiff.m4` etc) and put them, with your `python.m4` (and not including the extra headers test) into a new directory called `m4-safe`. bootstrap now removes all of m4/ and copies everything fresh of m4-safe. 

It should be a little simpler to maintain anyway.

**Comment by felixbuenemann** [comment]
I like the idea of splitting up a include.m4. 

Do we really need another directory to achieve that? We could just delete the hard coded list of m4 files from the m4 directory and blacklist them in gitignore…

**Comment by jcupitt** [comment]
The separate directory is a bit cleaner, I think. We can drop more .m4 files in there and we won't need to change .gitignore, or that `find` in bootstrap.

**Comment by felixbuenemann** [comment]
That's why I was suggesting to switch from whitelisting to blacklisting. I think the list of copied m4 files has been pretty static.

**Comment by felixbuenemann** [comment]
Btw. I think we don't need to copy those files mentioned by glib-gettextize at all. They are already in the aclocal search paths, so they will automatically be picked up by aclocal. We would only need to copy them, if they were outside the ACDIRS.

So I think we can save ourselves a lot of throuble by just ignoring the hint from `glib-gettextize` and maintain a single `m4` directory with custom macros.

This works fine on my mac, I'll have to verify on a few different linux versions to check if they behave differently.

**Comment by jcupitt** [comment]
I agree, let's try that. I've removed m4-safe on master.

**Comment by felixbuenemann** [comment]
Btw. I usually test such stuff on a feature branch, push to ci, see if everything works, fixup, rebase and repeat. Keeps the git history clean of all those oops and argh commits ;-)

**Comment by jcupitt** [comment]
Hehe yes, I should have done that. Overconfidence :(

**Pull request merged**
