### PR TITLE
Autofit text in the requested dimensions

### PR DESCRIPTION
**Pull request by gargsms**
This PR implements auto fitting of text in requested dimensions.

Two new flags were added to `vips text` to achieve this. `text` now supports `--height gint` and `--gravity VIPS_GRAVITY` to determine the position, and font size of the text automatically.

To autofit text, one needs to use `vips text` like:
```
vips text out.png "input text here" --font "Font Name" --width XXX --height XXX
```

The following table summarizes how different flags work to create a text output image. Font Size takes priority over others, and no autofit logic is applied if the user has specified a font size. The older behavior of `vips text` is preserved for user specified font size.

Font Size | Width | Height | Will text autofit?
--|--|--|--
✗ | ✗ | ✗ | ✗
✗ | ✓ | ✗ | ✗ 
✗ | ✗ | ✓ | ✗
✗ | ✓ | ✓ | ✓

As evident, `height` by itself does not have any effect on the autofit.

To make the process efficient, binary search is used to figure out the font size that has least deviation to requested dimensions. Incremental changes are made after a loosely fitting value of font size is obtained.

This is not a perfect working version of the implementation, it fails horribly for a single letter being autofit, however, it works just fine for most practical purposes. I have tested this thoroughly for edge cases, and have been using it in production for quite some time now. There is, however, quite some scope for improvement.

@jcupitt Comments welcomed. I have tried to maintain full backward compatibility, so any application using `vips text` the way it was before should not be harmed by this.

### CODE REVIEW

**Comment by gargsms** [comment]
There are a few shortcomings that should be rectified before this PR should be accepted.

- [ ] Text of a few characters cannot be fit reliably. `vips text out.png "I" --width 100 --height 100 --font "Sans"`
- [ ] Font name has to be specified with the text command always. `vips text out.png "some text" --width 100 --height 100` would default to `sans 12`
- [ ] The output image is 1-bit, so no color information can be written to the image

I will keep updating this comment as I further realize the shortcomings. :slightly_smiling_face:

**Comment by jcupitt** [comment]
8.6 is due in September, it'd be nice to get this in before then. I've added it to the 8.6 milestone.

**Comment by gargsms** [comment]
Ah, perfect. I will try to wrap this up by then. I had a few questions I will put here by the end of the day.

**Comment by jcupitt** [comment]
There are a few small style things I'd like to change, but the overall PR looks great.

I don't feel I can nag you to do the style stuff, so how about merging and I'll do a few changes after on master. Does that sounds OK? 

Thanks you for making this nice improvement!

**Comment by jcupitt** [comment]
I had an idea: how about adjusting DPI rather than the font name? It seems like a more natural way to size text, and you'd avoid all the string manipulation.

I would do a binary search, so:

* render at 72 dpi (the default)
* too large? halve the dpi; too small? double the dpi
* render again, until we have a dpi either side of the correct size
* now find the midpoint between the too-large and too-small dpi and try that
* keep finding midpoints until large - small is zero

You could make it converge a bit more quickly by assuming rendered size changes linearly with dpi and picking not the mid-point, but the proportion.

**Comment by gargsms** [comment]
Changing DPI did not occur to me, really - and with autofit, it doesn't have an affect on the rendered output either.I have a few improvements to do on this regarding gravity and positioning. I should be done in a day or two max.String manipulation was a hassle, yes. What are the style changes, exactly? I can confirm to the code convention if that is what you mean.  

    On Sunday, 17 September 2017 1:44 PM, John Cupitt <notifications@github.com> wrote:
 

 I had an idea: how about adjusting DPI rather than the font name? It seems like a more natural way to size text, and you'd avoid all the string manipulation.I would do a binary search, so:   
   - render at 72 dpi (the default)
   - too large? halve the dpi; too small? double the dpi
   - render again, until we have a dpi either side of the correct size
   - now find the midpoint between the too-large and too-small dpi and try that
   - keep finding midpoints until large - small is zero
You could make it converge a bit more quickly by assuming rendered size changes linearly with dpi and picking not the mid-point, but the proportion.—

**Comment by jcupitt** [comment]
I think the PR should use glib more, so gboolean not stdbool, GSList not the intrusive linked list, C++-style `//` comments should be avoided, enums need a `LAST` element and a gtk-doc comment, and the formatting should be in line with the rest of libvips. 

I can make these changes, I realize they are not really functional, and that getting the behaviour right is the important thing.

My dpi thought was that if the user specifies width and height but not dpi, dpi could be chosen to fit the text to the box.

**Comment by jcupitt** [comment]
What do you think about changing dpi rather than font size? Would that meet your needs for this feature?

**Comment by gargsms** [comment]
@jcupitt I have addressed some code conventions, removed `stdbool`. I tried to use GSList in place of the self-implemented Linked List, but gave up in between. I couldn't find exactly where the PR did not match the formatting, so I haven't fixed any of that.

Functionally, this works perfect at the moment. DPI would have no effect for text that is to be autofit, but would work just as expected if the font size is specified, or the autofit conditions are not met.

I, on purpose, did not change DPI, because I would have needed to rewrite most of the code. This works as intended. I can do that if it is required.

**Comment by jcupitt** [comment]
I like this feature, but I don't like all the string stuff with font size :( it feels wrong. I don't want to ask you to rewrite it, I'm sure you have better and more interesting things to do. 

How about we merge as is, then I'll switch it to change dpi instead? The effect would be the same (fit text to box), but the API would be slightly different, and you'd need to adapt upstream code a bit.

**Comment by gargsms** [comment]
I have no issues with you changing it. How much of a rewrite is that?

**Comment by gargsms** [comment]
Anyhow, I have another requirement on top of this. I would want to know the computed font size. ImageMagick exposes this in the metadata object for the image. Should we do the same here?
Also, since we support Pango Markup, is there a possibility to make the text a RGB image in place of 1-bit image? That should bring us on feature parity with ImageMagick.

**Comment by jcupitt** [comment]
It shouldn't be much work to make it change DPI rather than font size, let me merge to a branch and try.

Yes, we could expose computed dpi / points as an output param.

The output image is 8-bit, so you can do anti-aliased blends into an image, but you're right, it's not colour. 

You can add colour in the blend, I guess you know, eg.

```ruby
image = Vips::Image.text("hello world").ifthenelse(image, [255, 0, 0], blend: true)
```

To write `hello world` in red text on top of an image, but of course you can't change colour during the text.

**Comment by gargsms** [comment]
I have been using that to write the color to text, but it limits the possibilities with Pango Markup.
We can work on that accordingly once this is good enough. Thanks for the quick update.

**Comment by gargsms** [comment]
Tried changing the DPI settings on the latest vips master. It works as expected. I will try to work that out as you suggested.

    On Sunday, 17 September 2017 9:17 PM, Sukant Garg <garg_sms@yahoo.in> wrote:
 

 Changing DPI did not occur to me, really - and with autofit, it doesn't have an affect on the rendered output either.I have a few improvements to do on this regarding gravity and positioning. I should be done in a day or two max.String manipulation was a hassle, yes. What are the style changes, exactly? I can confirm to the code convention if that is what you mean.  

    On Sunday, 17 September 2017 1:44 PM, John Cupitt <notifications@github.com> wrote:
 

 I had an idea: how about adjusting DPI rather than the font name? It seems like a more natural way to size text, and you'd avoid all the string manipulation.I would do a binary search, so:   
   - render at 72 dpi (the default)
   - too large? halve the dpi; too small? double the dpi
   - render again, until we have a dpi either side of the correct size
   - now find the midpoint between the too-large and too-small dpi and try that
   - keep finding midpoints until large - small is zero
You could make it converge a bit more quickly by assuming rendered size changes linearly with dpi and picking not the mid-point, but the proportion.—

**Comment by jcupitt** [comment]
Oh dear, I had a go at changing the dpi:

https://github.com/jcupitt/libvips/tree/gargsms-text-autofit

It seems to work. I've not added gravity yet though.

**Comment by gargsms** [comment]
Wow. This is so much shorter. I will check if this works for my requirements.
It would have been better if I discussed that with you before implementing. Anyhow, if this works for me, I can implement gravity to this.

**Comment by jcupitt** [comment]
How about having gravity as a separate operation? You'd use it something like:

```ruby
mask = Vips::Image.text("hello", width: 100, height: 100).gravity(100, 100, direction: :north)
```

Now `text` expands to fit just within 100 x 100, then gravity expands to exactly 100 x 100, centred on the top edge. You could then combine `gravity` with other operations, like resize, perhaps. 

`gravity` is `embed` with x, y chosen for you, so it'd be simple to subclass that.

**Comment by gargsms** [comment]
That makes sense, actually.

**Comment by gargsms** [comment]
I tried your implementation. It works fine, but uses more iterations to fit the text, on an average, than the earlier implementation. I haven't yet tried to understand the code much.
I would make my app use your changes once they are in master. For now, I am using mine. Thanks.

**Comment by jcupitt** [comment]
Yes, I didn't try to get the iterations down, I'll see if I can improve that. I'll add a `gravity` operator too.

**Comment by gargsms** [comment]
Should I close this PR?

**Comment by jcupitt** [comment]
I added a `gravity` operator too, so this works:

```ruby
mask = Vips::Image.text("hello", width: 100, height: 100).gravity(:north, 100, 100)
```

Would you mind testing it? It you say it's OK, I'll merge to master and we can close. 

Supporting multi-coloured text is a separate issue I think.

**Comment by gargsms** [comment]
This seems to be work just fine. You should merge it and release.
Yes, working with coloured text is a different PR, or issue in itself.
Also, it is not necessary to credit me on this. Most of my code was useless anyway. :confused: 

Closing this.

**Comment by gargsms** [comment]
@jcupitt There is one probable shortcoming to adjusting the DPI to find an exact match. The computed font size of the rendered text may not be an integer in that case. So if we want to expose that as a property of the image, we would need to floor that first and then render.
I implemented that here: https://github.com/gargsms/libvips/commit/6adbd9ef7ff4507bc0cff37279bea985fa99781d

**Comment by jcupitt** [comment]
I'd forgotten about exposing the detected scale. Would it be enough to tag the dpi parameter as read-write? You can calculate font size from that.

**Comment by jcupitt** [comment]
I tried adding a new output param, I now see:

```
$ irb
irb(main):001:0> require 'vips'
=> true
irb(main):002:0> x = Vips::Image.text "hello", width: 100, height:100, autofit_dpi: true
=> [#<Image 98x48 uchar, 1 bands, b-w>, {"autofit_dpi"=>248}]
```

**Comment by jcupitt** [comment]
OK, merged to master! 8.6 soon, hopefully.

**Pull request closed without merging**
