### PR TITLE
Fixes for being able to build libvips in Visual Studio 2017 with an external project

### PR DESCRIPTION
**Pull request by angelmixu**
These are various fixes in order to build the library with my custom Visual Studio 2017 project.
My custom project is in this repository: https://github.com/angelmixu/libvips-vs2017

The explanation for the fixes are in the commit's comment.

Feel free to suggest, modify or comment them.

### CODE REVIEW

**Comment by jcupitt** [comment]
Hi @angelmixu, this is great, I'll have a look through it and comment.

**Comment by jcupitt** [comment]
No comments, it all looks good. You found a couple of nasty errors too. I guess clang allows arithmetic on `void*` as well, since libvips compiles OK on that too.

I wonder whether updating libvipsCC is a good idea. It's deprecated now and disabled by default in git master. The changes are small though, so why not.

**Comment by jcupitt** [comment]
I pushed a few changes to fix compiler warnings with gcc, and added a line to the changelog. https://github.com/jcupitt/libvips/commit/0c8552d3fc90e04fc49e931f14978924e5d887cb

**Comment by angelmixu** [comment]
Thanks!!! :)

**Pull request merged**
