### PR TITLE
Adds a sample multi-page TIFF

### PR DESCRIPTION
**Pull request by harukizaemon**
Adds a sample multi-page TIFF for https://github.com/jcupitt/ruby-vips/issues/91.

**WARNING:** if you're squeamish, it's a 3D rat's heart.

### CODE REVIEW

**Comment by jcupitt** [comment]
It seems to work! I see:

```
john@kiwi:~/pics$ time vips copy multi-page.tif[n=-1] x.v
vips warning: tiff2vips: no resolution information for TIFF image "multi-page.tif" -- defaulting to 1 pixel per mm
vips warning: tiff2vips: no resolution information for TIFF image "multi-page.tif" -- defaulting to 1 pixel per mm
real	0m0.265s
user	0m0.336s
sys	0m0.200s
```

So about 0.2s for the load. `n=-1` means load all pages, or you can do `page=12,n=3` to load pages 12, 13, 14.

`x.v` is a toilet roll, so you see 526 x 28431 (which is 351 * 81) pixels, with `page-height` set to the length of each sheet.

```
$ vipsheader -a x.v
x.v: 526x28431 uchar, 1 band, b-w, tiffload
width: 526
height: 28431
bands: 1
format: uchar
coding: none
interpretation: b-w
xoffset: 0
yoffset: 0
xres: 1
yres: 1
filename: x.v
xml-header: VIPS_TYPE_AREA, count = 1, data = 0x565231cc8610
vips-loader: tiffload
page-height: 351
image-description: ImageJ=1.51a
images=81
slices=81
loop=false
min=35.0
max=138.0
orientation: 1
```

**Comment by jcupitt** [comment]
I've not merged your test image, I think it's too large :( I'll try making a smaller one. 

I work on lung disease, so I'm not able to be squeamish :( What kind of scanner is it from? The detail is lovely. I'm mostly micro PET, which is awful.

**Comment by jcupitt** [comment]
OK, merged to master (though with a slightly smaller test image).

**Comment by harukizaemon** [comment]
Finally got around to using this in production and it looks like the `n` argument for `tiffload` isn't recognised (or I'm doing something wrong):

```
irb --> image = Vips::Image.tiffload(file, n: -1)
Vips::Error: No such option 'n',
	from ruby-vips-1.0.4/lib/vips/call.rb:165:in `block in set_optional_input'
	from ruby-vips-1.0.4/lib/vips/call.rb:155:in `each'
	from ruby-vips-1.0.4/lib/vips/call.rb:155:in `set_optional_input'
	from ruby-vips-1.0.4/lib/vips/call.rb:247:in `invoke'
	from ruby-vips-1.0.4/lib/vips/call.rb:278:in `call_base'
	from ruby-vips-1.0.4/lib/vips/image.rb:400:in `method_missing'
	from (irb):13
```

**Comment by harukizaemon** [comment]
@jcupitt Nevermind! I realise this is functionality slated for 8.5 - currently using 8.4.5.

**Comment by jcupitt** [comment]
Yes, due in a few weeks, hopefully.

**Pull request closed without merging**
