### PR TITLE
Remove some g-ir-scanner warnings

### PR DESCRIPTION
**Pull request by astavale**

### CODE REVIEW

**Comment by jcupitt** [comment]
Useful!

**Comment by astavale** [comment]
Well, useful to me as I had enabled warnings while I worked on updating the gobject annotations :)

**Comment by jcupitt** [comment]
I wasn't being sarcastic! It's great you're fixing all this stuff.

**Comment by astavale** [comment]
Thanks! I'm pretty much finished updating the current GObject introspection annotations. Working on this has made me more convinced there should be a g-o-i binding that fits in with g-o-i idioms, but I'll write up a much more detailed proposal at another time.

**Pull request merged**
