### PR TITLE
Add hsv

### PR DESCRIPTION
**Pull request by Jondeen**
Converts should be working both ways

### CODE REVIEW

**Comment by Jondeen** [comment]
Does the failed travis build @ d3307d1 mean anything?

**Comment by jcupitt** [comment]
Yes, there was a duplicate case in a switch. I'll fix it up and try to make a neat patch against master.

**Comment by Jondeen** [comment]
Ah I see. Thanks!

**Comment by jcupitt** [comment]
Hi again, I've fixed up my add-hsv branch a bit: I've added some docs, added some tests, it all seems to pass the test-suite now. What do you think? I'll merge to master if you give a thumbs-up.

**Comment by Jondeen** [comment]
Hi!

I only got two thumbs, but they're both pointing in a vertically and approvingly positive direction.

**Comment by jcupitt** [comment]
OK, merged here:

https://github.com/jcupitt/libvips/compare/14dfda4e02...a812e90332

Thanks for working on this! I added you to the ChangeLog.

**Pull request merged**
