### PR TITLE
Remove files generated by glib-mkenums from version control

### PR DESCRIPTION
**Pull request by astavale**

### CODE REVIEW

**Comment by jcupitt** [comment]
Hello, could you explain your reasoning for removing these files?

They were added to version control to remove the perl dependency when building from git -- it was causing confusion and delay on some platforms. 

If they were regenerated on every autogen / make then I'd agree they should not be under source control, but they are only remade when a few of the vips headers are changed, so (imo) it's OK to have them stored.

**Comment by astavale** [comment]
I wanted to stop them appearing as modified files when I did `git status`. When I investigated further I found they can be built on every clean build. So I added them to the CLEANFILES in the Makefile.am and to `.gitgnore`.

If the dependency of glib-mkenums on Perl is the problem then `libvips/include/vips/enumtypes.h` and `libvips/iofuncs/enumtypes.c` should just be updated in git.

I've just cloned a clean copy and only `include/vips/enumtypes.h` is showing as modified. A copy from a month ago is also showing `libvips/iofuncs/enumtypes.c` as modified. That was after `make distclean`. Not sure what is going on with that one.

**Comment by jcupitt** [comment]
8.5 will (annoyingly) rebuild them constantly, but master will (should) only rebuild them if you edit the headers they depend on. 

https://github.com/jcupitt/libvips/commit/653e99ea8239c8c3a4ae04c20f259c640e8b9cd5

**Comment by astavale** [comment]
I've just done:

```git clone https://github.com/jcupitt/libvips
cd libvips
./autogen.sh
make
```

and `git status` shows `libvips/include/vips/enumtypes.h` as modified. It's a minor distraction, but if I was to use `git add .` it will get picked up.

My installed `glib-mkenums` version is `glib-2.46.2`. It looks as though it has re-ordered some of the symbols (github won't let me attach a diff!):

```
diff --git a/libvips/include/vips/enumtypes.h b/libvips/include/vips/enumtypes.h
index 545d8f6..122a612 100644
--- a/libvips/include/vips/enumtypes.h
+++ b/libvips/include/vips/enumtypes.h
@@ -6,6 +6,32 @@
 
 G_BEGIN_DECLS
 
+/* enumerations from "../../../libvips/include/vips/resample.h" */
+GType vips_kernel_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_KERNEL (vips_kernel_get_type())
+GType vips_size_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_SIZE (vips_size_get_type())
+/* enumerations from "../../../libvips/include/vips/foreign.h" */
+GType vips_foreign_flags_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_FOREIGN_FLAGS (vips_foreign_flags_get_type())
+GType vips_saveable_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_SAVEABLE (vips_saveable_get_type())
+GType vips_foreign_webp_preset_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_FOREIGN_WEBP_PRESET (vips_foreign_webp_preset_get_type())
+GType vips_foreign_tiff_compression_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_FOREIGN_TIFF_COMPRESSION (vips_foreign_tiff_compression_get_type())
+GType vips_foreign_tiff_predictor_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_FOREIGN_TIFF_PREDICTOR (vips_foreign_tiff_predictor_get_type())
+GType vips_foreign_tiff_resunit_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_FOREIGN_TIFF_RESUNIT (vips_foreign_tiff_resunit_get_type())
+GType vips_foreign_png_filter_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_FOREIGN_PNG_FILTER (vips_foreign_png_filter_get_type())
+GType vips_foreign_dz_layout_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_FOREIGN_DZ_LAYOUT (vips_foreign_dz_layout_get_type())
+GType vips_foreign_dz_depth_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_FOREIGN_DZ_DEPTH (vips_foreign_dz_depth_get_type())
+GType vips_foreign_dz_container_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_FOREIGN_DZ_CONTAINER (vips_foreign_dz_container_get_type())
 /* enumerations from "../../../libvips/include/vips/arithmetic.h" */
 GType vips_operation_math_get_type (void) G_GNUC_CONST;
 #define VIPS_TYPE_OPERATION_MATH (vips_operation_math_get_type())
@@ -23,14 +49,6 @@ GType vips_operation_complex2_get_type (void) G_GNUC_CONST;
 #define VIPS_TYPE_OPERATION_COMPLEX2 (vips_operation_complex2_get_type())
 GType vips_operation_complexget_get_type (void) G_GNUC_CONST;
 #define VIPS_TYPE_OPERATION_COMPLEXGET (vips_operation_complexget_get_type())
-/* enumerations from "../../../libvips/include/vips/basic.h" */
-GType vips_precision_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_PRECISION (vips_precision_get_type())
-/* enumerations from "../../../libvips/include/vips/colour.h" */
-GType vips_intent_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_INTENT (vips_intent_get_type())
-GType vips_pcs_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_PCS (vips_pcs_get_type())
 /* enumerations from "../../../libvips/include/vips/conversion.h" */
 GType vips_extend_get_type (void) G_GNUC_CONST;
 #define VIPS_TYPE_EXTEND (vips_extend_get_type())
@@ -44,33 +62,9 @@ GType vips_angle45_get_type (void) G_GNUC_CONST;
 #define VIPS_TYPE_ANGLE45 (vips_angle45_get_type())
 GType vips_interesting_get_type (void) G_GNUC_CONST;
 #define VIPS_TYPE_INTERESTING (vips_interesting_get_type())
-/* enumerations from "../../../libvips/include/vips/convolution.h" */
-GType vips_combine_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_COMBINE (vips_combine_get_type())
-/* enumerations from "../../../libvips/include/vips/draw.h" */
-GType vips_combine_mode_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_COMBINE_MODE (vips_combine_mode_get_type())
-/* enumerations from "../../../libvips/include/vips/foreign.h" */
-GType vips_foreign_flags_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_FOREIGN_FLAGS (vips_foreign_flags_get_type())
-GType vips_saveable_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_SAVEABLE (vips_saveable_get_type())
-GType vips_foreign_webp_preset_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_FOREIGN_WEBP_PRESET (vips_foreign_webp_preset_get_type())
-GType vips_foreign_tiff_compression_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_FOREIGN_TIFF_COMPRESSION (vips_foreign_tiff_compression_get_type())
-GType vips_foreign_tiff_predictor_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_FOREIGN_TIFF_PREDICTOR (vips_foreign_tiff_predictor_get_type())
-GType vips_foreign_tiff_resunit_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_FOREIGN_TIFF_RESUNIT (vips_foreign_tiff_resunit_get_type())
-GType vips_foreign_png_filter_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_FOREIGN_PNG_FILTER (vips_foreign_png_filter_get_type())
-GType vips_foreign_dz_layout_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_FOREIGN_DZ_LAYOUT (vips_foreign_dz_layout_get_type())
-GType vips_foreign_dz_depth_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_FOREIGN_DZ_DEPTH (vips_foreign_dz_depth_get_type())
-GType vips_foreign_dz_container_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_FOREIGN_DZ_CONTAINER (vips_foreign_dz_container_get_type())
+/* enumerations from "../../../libvips/include/vips/util.h" */
+GType vips_token_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_TOKEN (vips_token_get_type())
 /* enumerations from "../../../libvips/include/vips/image.h" */
 GType vips_demand_style_get_type (void) G_GNUC_CONST;
 #define VIPS_TYPE_DEMAND_STYLE (vips_demand_style_get_type())
@@ -84,23 +78,29 @@ GType vips_coding_get_type (void) G_GNUC_CONST;
 #define VIPS_TYPE_CODING (vips_coding_get_type())
 GType vips_access_get_type (void) G_GNUC_CONST;
 #define VIPS_TYPE_ACCESS (vips_access_get_type())
+/* enumerations from "../../../libvips/include/vips/colour.h" */
+GType vips_intent_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_INTENT (vips_intent_get_type())
+GType vips_pcs_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_PCS (vips_pcs_get_type())
+/* enumerations from "../../../libvips/include/vips/operation.h" */
+GType vips_operation_flags_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_OPERATION_FLAGS (vips_operation_flags_get_type())
+/* enumerations from "../../../libvips/include/vips/convolution.h" */
+GType vips_combine_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_COMBINE (vips_combine_get_type())
 /* enumerations from "../../../libvips/include/vips/morphology.h" */
 GType vips_operation_morphology_get_type (void) G_GNUC_CONST;
 #define VIPS_TYPE_OPERATION_MORPHOLOGY (vips_operation_morphology_get_type())
+/* enumerations from "../../../libvips/include/vips/draw.h" */
+GType vips_combine_mode_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_COMBINE_MODE (vips_combine_mode_get_type())
+/* enumerations from "../../../libvips/include/vips/basic.h" */
+GType vips_precision_get_type (void) G_GNUC_CONST;
+#define VIPS_TYPE_PRECISION (vips_precision_get_type())
 /* enumerations from "../../../libvips/include/vips/object.h" */
 GType vips_argument_flags_get_type (void) G_GNUC_CONST;
 #define VIPS_TYPE_ARGUMENT_FLAGS (vips_argument_flags_get_type())
-/* enumerations from "../../../libvips/include/vips/operation.h" */
-GType vips_operation_flags_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_OPERATION_FLAGS (vips_operation_flags_get_type())
-/* enumerations from "../../../libvips/include/vips/resample.h" */
-GType vips_kernel_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_KERNEL (vips_kernel_get_type())
-GType vips_size_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_SIZE (vips_size_get_type())
-/* enumerations from "../../../libvips/include/vips/util.h" */
-GType vips_token_get_type (void) G_GNUC_CONST;
-#define VIPS_TYPE_TOKEN (vips_token_get_type())
 G_END_DECLS
 
 #endif /*VIPS_ENUM_TYPES_H*/
```

**Comment by jcupitt** [comment]
Yes, I was just trying this too. It's rebuilding `include/vips/enumtypes.h`, though not `iofuncs/enumtypes.c`, mysteriously.

Different glib versions will produce slightly different `enumtypes.h`.

**Comment by astavale** [comment]
`git status` still shows `libvips/include/vips/enumtypes.h` as modified after a clean download and first time build from master. I can then do `git checkout libvips/include/vips/enumtypes.h` and that makes `git status` report a clean working directory. So I will close this, unless there are better suggestions.

**Pull request closed without merging**
